### PR TITLE
[FEAT] NEPS integration, improved logging, custom seed keyword

### PR DESCRIPTION
**Pull request by becktepe**
By adding an additional `seed_keyword` argument, users can overwrite the default `seed` override that is applied if seeds are supplied. It allows to use arbitrary key values, e.g., `fold` to not interfere with a global seed.

### CODE REVIEW

**Comment by TheEimer** [comment]
Sounds reasonable! But why is the test failing so strangely?

**Comment by becktepe** [comment]
Yes, this is really strange. The repo version based on which I created the fork passed all tests so I don't see why this one should fail. I could try to sync the fork to a new repo version (assuming all tests are passed) and create a new PR

**Comment by becktepe** [comment]
With these commits I added the following updates:

1. Added HyperNEPS, a [NePS](https://github.com/automl/neps) integration ✨ 
2. Updated logging of _history_ and _incumbents_. The history now contains the mean performance as well as the performance per seed when using seeds. The incumbents are stored in a similar format, including the same metrics as before but now in csv format to make processing/visualizations easier. Additionally, both are stored after each iteration to use them during optimization and in case of aborted runs.

The features are tested for the MLP task with SMAC-MF, PriorBand and ASHA

**Comment by becktepe** [comment]
There still seems to be a problem with conflicting dependencies. I will look into that soon

**Comment by TheEimer** [comment]
Does it work with uv? I want to switch everything over to that anyway, so I can do that sooner rather than later and take a look here again.

**Comment by becktepe** [comment]
What do you mean by uv?

**Comment by TheEimer** [comment]
This: https://github.com/astral-sh/uv

**Comment by becktepe** [comment]
Seems to be working now :D

**Pull request merged**
